const skillsArray = [
    "Academic tutoring",
    "Exam preparation assistance",
    "Study group facilitation",
    "Home repair and maintenance",
    "Painting and decorating",
    "Cleaning services",
    "Tech support and troubleshooting",
    "Computer programming",
    "Website development",
    "Drawing and painting",
    "Craft making",
    "Photography",
    "Fitness coaching",
    "Yoga instruction",
    "Nutrition advice",
    "Gardening and landscaping",
    "Outdoor event organization",
    "Nature walks or hiking guidance",
    "Pet sitting",
    "Dog walking",
    "Pet grooming",
    "Language learning assistance",
    "Translation services",
    "Cooking lessons",
    "Meal planning assistance",
    "Catering services",
    "Party planning",
    "Event coordination",
    "Wedding planning assistance",
    "Car maintenance",
    "Basic auto repairs",
    "Car cleaning services",
    "Budgeting advice",
    "Financial planning assistance",
    "Counseling services",
    "Emotional support",
    "Volunteering coordination",
    "Community project management",
    "Logo design",
    "Graphic design services",
    "Home security consultation",
    "Personal safety advice",
    "Copywriting",
    "Editing and proofreading",
    "Ride-sharing assistance",
    "Grocery or goods delivery",
    "DIY project assistance",
    "Home improvement advice",
    "Career coaching",
    "Mentorship programs"
  ];


export const skillList = skillsArray;